title: ENOWARS Blog
email: agrs.techteam@guv.tu-berlin.de
description: HAX HAX
url: https://github.com/enowars
twitter_username: ENOFLAG
theme: jekyll-theme-hacker

paginate: 3

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  
